namespace iKnow.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AddFourSeedUsersQuestionsAnswers : DbMigration
    {
        public override void Up()
        {
            Sql(@"
DELETE FROM [dbo].[Topics]

SET IDENTITY_INSERT [dbo].[Topics] ON
INSERT INTO [dbo].[Topics] ([Id], [Name], [Description]) VALUES (13, N'Software Engineering', N'Software engineering is the process of analyzing user needs and designing, constructing, and testing end user applications that will satisfy these needs through the use of software programming languages. It is the application of engineering principles to software development. 

In contrast to simple programming, software engineering is used for larger and more complex software systems, which are used as critical systems for businesses and organizations.')
INSERT INTO [dbo].[Topics] ([Id], [Name], [Description]) VALUES (14, N'New Zealand', N'New Zealand is an island country located in the southwestern Pacific Ocean comprising two main landmasses (the North Island and the South Island) and numerous smaller islands. 

The geography of New Zealand is highly varied, from snowcapped mountains to lowland plains. The government system is a parliamentary democracy and a Commonwealth realm; the chief of state is the queen of the United Kingdom, and the head of government is the prime minister. New Zealand has a free market economy in which the prices of goods and services are determined in a free price system.')
INSERT INTO [dbo].[Topics] ([Id], [Name], [Description]) VALUES (15, N'Internet', N'The Internet is the global system of interconnected computer networks that use the Internet protocol suite (TCP/IP) to link devices worldwide. It is a network of networks that consists of private, public, academic, business, and government networks of local to global scope, linked by a broad array of electronic, wireless, and optical networking technologies.')
INSERT INTO [dbo].[Topics] ([Id], [Name], [Description]) VALUES (16, N'Artificial Intelligence', N'Artificial intelligence is a science and technology based on disciplines such as Computer Science, Biology, Psychology, Linguistics, Mathematics, and Engineering. A major thrust of AI is in the development of computer functions associated with human intelligence, such as reasoning, learning, and problem solving.')
INSERT INTO [dbo].[Topics] ([Id], [Name], [Description]) VALUES (17, N'History', N'The study of past events, particularly in human affairs.')
INSERT INTO [dbo].[Topics] ([Id], [Name], [Description]) VALUES (18, N'Travel', N'Travel is the movement of people between relatively distant geographical locations, and can involve travel by foot, bicycle, automobile, train, boat, bus, airplane, or other means, with or without luggage, and can be one way or round trip. Travel can also include relatively short stays between successive movements.')
INSERT INTO [dbo].[Topics] ([Id], [Name], [Description]) VALUES (19, N'Web Development', N'Web development is a broad term for the work involved in developing a web site for the Internet (World Wide Web) or an intranet (a private network).')
INSERT INTO [dbo].[Topics] ([Id], [Name], [Description]) VALUES (20, N'Health', N'Health is the level of functional and metabolic efficiency of a living organism. In humans it is the ability of individuals or communities to adapt and self-manage when facing physical, mental, psychological and social changes with environment.')
INSERT INTO [dbo].[Topics] ([Id], [Name], [Description]) VALUES (21, N'Automobile', N'An automobile (or a car) is a wheeled motor vehicle used for transportation. Most definitions of car say they run primarily on roads, seat one to eight people, have four tires, and mainly transport people rather than goods.')
INSERT INTO [dbo].[Topics] ([Id], [Name], [Description]) VALUES (22, N'Environment', N'Environment is everything that is around us. It can be living or nonliving things. It includes physical, chemical and other natural forces. Living things live in their environment. They constantly interact with it and adapt themselves to conditions in their environment.')
INSERT INTO [dbo].[Topics] ([Id], [Name], [Description]) VALUES (23, N'Sport', N'Sport includes all forms of competitive physical activity or games which, through casual or organised participation, aim to use, maintain or improve physical ability and skills while providing enjoyment to participants, and in some cases, entertainment for spectators.')
INSERT INTO [dbo].[Topics] ([Id], [Name], [Description]) VALUES (24, N'Economics', N'Economics is the social science that studies the production, distribution, and consumption of goods and services. Economics focuses on the behaviour and interactions of economic agents and how economies work.')
INSERT INTO [dbo].[Topics] ([Id], [Name], [Description]) VALUES (25, N'Education', N'Education is the process of facilitating learning, or the acquisition of knowledge, skills, values, beliefs, and habits. Educational methods include storytelling, discussion, teaching, training, and directed research.')
INSERT INTO [dbo].[Topics] ([Id], [Name], [Description]) VALUES (26, N'Lifestyle', N'Lifestyle is the interests, opinions, behaviours, and behavioural orientations of an individual, group, or culture.')
INSERT INTO [dbo].[Topics] ([Id], [Name], [Description]) VALUES (27, N'International Relations', N'International relations (IR) or international affairs, depending on academic institution, is either a field of political science, an interdisciplinary academic field similar to global studies, or an entirely independent academic discipline in which students take a variety of internationally focused courses in social science and humanities disciplines.')
INSERT INTO [dbo].[Topics] ([Id], [Name], [Description]) VALUES (28, N'Country', N'A country is a region that is identified as a distinct national entity in political geography. A country may be an independent sovereign state or one that is occupied by another state, as a non-sovereign or formerly sovereign political division, or a geographic region associated with sets of previously independent or differently associated people with distinct political characteristics.')
INSERT INTO [dbo].[Topics] ([Id], [Name], [Description]) VALUES (29, N'Interpersonal Communication', N'Interpersonal communication is an exchange of information between two or more people. It is also an area of study and research that seeks to understand how humans use verbal and nonverbal cues to accomplish a number of personal and relational goals.')
INSERT INTO [dbo].[Topics] ([Id], [Name], [Description]) VALUES (30, N'Google', N'Google is an American multinational technology company that specializes in Internet-related services and products. These include online advertising technologies, search, cloud computing, software, and hardware.')
INSERT INTO [dbo].[Topics] ([Id], [Name], [Description]) VALUES (31, N'Huawei', N'Huawei Technologies Co., Ltd. is a Chinese multinational networking and telecommunications equipment and services company headquartered in Shenzhen, Guangdong. It is the largest telecommunications equipment manufacturer in the world, having overtaken Ericsson in 2012.')
INSERT INTO [dbo].[Topics] ([Id], [Name], [Description]) VALUES (32, N'China', N'China is a country in East Asia bordering the East China Sea, Korea Bay, and the South China Sea. Neighboring countries include 14 sovereign states. The terrain is diverse in China with mostly mountains along with deserts in the west and plains in the east.')
INSERT INTO [dbo].[Topics] ([Id], [Name], [Description]) VALUES (33, N'Full Stack Developer', N'The industry definition of a Full Stack Developer is an engineer who can work on different levels of an application stack. The term stack refers to the combination of components and tools that make up the application. The components could be in the front-end or the back-end of the system.

The main objective of full stack engineer is to keep every part of the system running smoothly. A Full Stack Developer can performs tasks ranging from resizing an image or text in a webpage to patching the kernel.')
INSERT INTO [dbo].[Topics] ([Id], [Name], [Description]) VALUES (34, N'Food', N'Food is any substance[1] consumed to provide nutritional support for an organism. It is usually of plant or animal origin, and contains essential nutrients, such as carbohydrates, fats, proteins, vitamins, or minerals. The substance is ingested by an organism and assimilated by the organism''s cells to provide energy, maintain life, or stimulate growth.')
INSERT INTO [dbo].[Topics] ([Id], [Name], [Description]) VALUES (35, N'America', N'The U.S. is a country of 50 states covering a vast swath of North America, with Alaska in the northwest and Hawaii extending the nation¡¯s presence into the Pacific Ocean. Major Atlantic Coast cities are New York, a global finance and culture center, and capital Washington, DC. Midwestern metropolis Chicago is known for influential architecture and on the west coast, Los Angeles'' Hollywood is famed for filmmaking.')
INSERT INTO [dbo].[Topics] ([Id], [Name], [Description]) VALUES (36, N'Business', N'A business (also known as an enterprise, a company, or a firm) is an organizational entity and legal entity made up of an association of people, be they natural, legal, or a mixture of both who share a common purpose and unite in order to focus their various talents and organize their collectively available skills or resources to achieve specific declared goals and are involved in the provision of goods and services to consumers. A business can also be described as an organisation that provides goods and services for human needs.')
INSERT INTO [dbo].[Topics] ([Id], [Name], [Description]) VALUES (37, N'Movie', N'Movies, also known as films, are a type of visual communication which uses moving pictures and sound to tell stories or inform (help people to learn). 

People in every part of the world watch movies as a type of entertainment, a way to have fun. For some people, fun movies can mean movies that make them laugh, while for others it can mean movies that make them cry, or feel afraid.')
INSERT INTO [dbo].[Topics] ([Id], [Name], [Description]) VALUES (38, N'Music', N'Music is a form of art; an expression of emotions through harmonic frequencies. Music is also a form of entertainment that puts sounds together in a way that people like, find interesting or dance to. Most music includes people singing with their voices or playing musical instruments, such as the piano, guitar, drums or violin.')
INSERT INTO [dbo].[Topics] ([Id], [Name], [Description]) VALUES (39, N'Philosophy', N'Philosophy is a way of thinking about the world, the universe, and society. It works by asking very basic questions about the nature of human thought, the nature of the universe, and the connections between them. The ideas in philosophy are often general and abstract. But this does not mean that philosophy is not about the real world. Ethics, for example, asks about the ideas underlying our everyday lives. Metaphysics asks about how the world works and of what it is made.')
INSERT INTO [dbo].[Topics] ([Id], [Name], [Description]) VALUES (40, N'Physics', N'Physics is the natural science that involves the study of matter and its motion and behavior through space and time, along with related concepts such as energy and force.')
INSERT INTO [dbo].[Topics] ([Id], [Name], [Description]) VALUES (41, N'Mobile Phone', N'A mobile phone, known as a cell phone in North America, is a portable telephone that can make and receive calls over a radio frequency link while the user is moving within a telephone service area.')
INSERT INTO [dbo].[Topics] ([Id], [Name], [Description]) VALUES (42, N'Earth', N'Earth is the planet we live on. It is the third planet from the sun. It is the only planet known to have life on it. Lots of scientists think the earth formed around 4.5 billion years ago. It is one of four rocky planets on the inside of the Solar System. The other three are Mercury, Venus and Mars.')
INSERT INTO [dbo].[Topics] ([Id], [Name], [Description]) VALUES (43, N'Programming Language', N'A programming language is a type of written language that tells computers what to do in order to work. Programming languages are used to make all the computer programs and computer software. A programming language is like a set of instructions that the computer follows to do something.')
INSERT INTO [dbo].[Topics] ([Id], [Name], [Description]) VALUES (44, N'Photography', N'Photography is a way of making a picture using a camera. A person who makes pictures using a camera is called a photographer. A picture made using a camera is called a photograph or photo.')
SET IDENTITY_INSERT [dbo].[Topics] OFF

                INSERT INTO [dbo].[AspNetUsers] ([Email], [EmailConfirmed], [PasswordHash], [SecurityStamp], [PhoneNumber], [PhoneNumberConfirmed], [TwoFactorEnabled], [LockoutEndDateUtc], [LockoutEnabled], [AccessFailedCount], [UserName], [Id], [FirstName], [LastName], [Intro], [Gender], [Location], [DefaultIconNumber]) VALUES (N'JasonSlavin@iknow.com', 0, N'AH/AgUtAmg9ujyeZAvGGF1vO6EXVW7U4K+zPctoamoeTMpJ8uSx0hywJC7BJCegkfQ==', N'cae21731-56c6-41da-944c-120028224015', NULL, 0, 0, NULL, 0, 0, N'jasonslavin0', N'aa32eb82-d698-468e-8c0b-dc3a6bebfc12', N'Jason', N'Slavin', N'Front End Developer (2017-present)', 1, NULL, 2)
INSERT INTO [dbo].[AspNetUsers] ([Email], [EmailConfirmed], [PasswordHash], [SecurityStamp], [PhoneNumber], [PhoneNumberConfirmed], [TwoFactorEnabled], [LockoutEndDateUtc], [LockoutEnabled], [AccessFailedCount], [UserName], [Id], [FirstName], [LastName], [Intro], [Gender], [Location], [DefaultIconNumber]) VALUES (N'AbhinavRajendran@iknow.com', 0, N'AGdmAHKW/W689LO+m5C7htxA0LH0D9Fa0e/k0VwJh916XXTYb1VzeRqCjBv7PU+PxQ==', N'444798b1-7e44-40c0-99e8-ab09f4f200d0', NULL, 0, 0, NULL, 0, 0, N'abhinavrajendran0', N'e40ee71a-e3de-4b33-a877-0cc91fdcb337', N'Abhinav', N'Rajendran', NULL, 1, NULL, 9)
INSERT INTO [dbo].[AspNetUsers] ([Email], [EmailConfirmed], [PasswordHash], [SecurityStamp], [PhoneNumber], [PhoneNumberConfirmed], [TwoFactorEnabled], [LockoutEndDateUtc], [LockoutEnabled], [AccessFailedCount], [UserName], [Id], [FirstName], [LastName], [Intro], [Gender], [Location], [DefaultIconNumber]) VALUES (N'BenKolber@iknow.com', 0, N'AF3b36JA+NPqIgKlCZZGYnR1pjsHrMVreM0KyGrMynh1CyT/IHVNQJ9y14RJ362Szg==', N'3d6d607f-9aea-4873-b010-5ddcaddfa652', NULL, 0, 0, NULL, 0, 0, N'benkolber0', N'eb5d625e-aa8f-4709-a296-f92b1df0dd3e', N'Ben', N'Kolber', N'Former paratrooper, now I cook and code.', 1, NULL, 2)
INSERT INTO [dbo].[AspNetUsers] ([Email], [EmailConfirmed], [PasswordHash], [SecurityStamp], [PhoneNumber], [PhoneNumberConfirmed], [TwoFactorEnabled], [LockoutEndDateUtc], [LockoutEnabled], [AccessFailedCount], [UserName], [Id], [FirstName], [LastName], [Intro], [Gender], [Location], [DefaultIconNumber]) VALUES (N'liefuzhangnz@gmail.com', 0, N'AFpRj14+Wv+TibaWASAYIoUdgePP/RxpWIh2BbgAH7n+cdKo9TJkRs47DAZYoXYDfA==', N'fc3f35c1-4ddf-4394-8434-1ebe21e86856', NULL, 0, 0, NULL, 0, 0, N'liefuzhang0', N'fe8c5539-5945-4cfb-9892-6cb4d3935c90', N'Liefu', N'Zhang', NULL, 0, NULL, 4)

SET IDENTITY_INSERT [dbo].[Questions] ON
INSERT INTO [dbo].[Questions] ([Id], [Title], [Description], [AppUserId]) VALUES (18, N'What are the signs that you are a skilled software developer?', N'To be a developer is easy, but to be a skilled developer is hard. What characteristics does a skilled developer have?', N'fe8c5539-5945-4cfb-9892-6cb4d3935c90')
INSERT INTO [dbo].[Questions] ([Id], [Title], [Description], [AppUserId]) VALUES (19, N'How can full stack developers learn so many skills?', N'Full-Stack Web Development, according to the Stack Overflow 2016 Developer Survey, is the most popular developer occupation today.', N'fe8c5539-5945-4cfb-9892-6cb4d3935c90')
INSERT INTO [dbo].[Questions] ([Id], [Title], [Description], [AppUserId]) VALUES (21, N'What are some of the best ways to learn programming?', NULL, N'aa32eb82-d698-468e-8c0b-dc3a6bebfc12')
INSERT INTO [dbo].[Questions] ([Id], [Title], [Description], [AppUserId]) VALUES (22, N'What’s one inaccuracy in a science fiction movie that drives you crazy?', NULL, N'fe8c5539-5945-4cfb-9892-6cb4d3935c90')
SET IDENTITY_INSERT [dbo].[Questions] OFF

INSERT INTO [dbo].[TopicQuestions] ([TopicId], [QuestionId]) VALUES (18, 13)
INSERT INTO [dbo].[TopicQuestions] ([TopicId], [QuestionId]) VALUES (19, 13)
INSERT INTO [dbo].[TopicQuestions] ([TopicId], [QuestionId]) VALUES (21, 13)
INSERT INTO [dbo].[TopicQuestions] ([TopicId], [QuestionId]) VALUES (19, 19)
INSERT INTO [dbo].[TopicQuestions] ([TopicId], [QuestionId]) VALUES (22, 37)
INSERT INTO [dbo].[TopicQuestions] ([TopicId], [QuestionId]) VALUES (21, 43)

SET IDENTITY_INSERT [dbo].[Answers] ON
INSERT INTO [dbo].[Answers] ([Id], [Content], [CreatedDate], [QuestionId], [AppUserId], [UpdatedDate]) VALUES (16, N'<p>There is a really great part of the film “Gran Torino” where he brings the kid into his garage. The kid sees all of his tools and is astonished, saying “I can’t afford to buy all this stuff” to which Eastwood’s character replies “Even a bonehead like you can understand that a man acquires this over a period of 50 years”. But he then gives the kid some vice-grips, wd-40, and duct tape, and says he could keep it, and that he could solve a lot of household issues with those.</p><p>Despite the rudeness of his statement, there is truth to it, especially for programmers.</p><p>I was a beginner, not so long ago, and I remember thinking to myself the same thing “how am I gonna learn all this stuff, I don’t have time for it and there is so much!”</p><p>The truth is, you acquire each skill / tool / language over time. Certainly, it is harder for us as programmers since Libraries and Frameworks seem to spring out of the ground and have surprising complexity, but it gets easier to learn new things, and there is familiarity that grows with use. As you progress in your career, you will have to learn new things, new skills, new tools, but your ability to use the old ones doesn’t just disappear, and some of the underlying structures of all that we do as developers does not move as quickly as the languages do.</p><p>So essentially, time is how. It just takes time. When you look at the entirety of the full range of tools in the tech stack, thinking that is what you have to take on, you’ll get buried. But if you focus on small parts of it and acquire ability in that chosen discipline, you can then move on to another, and add it to your tool belt.</p>', N'2018-01-17 16:34:31', 19, N'aa32eb82-d698-468e-8c0b-dc3a6bebfc12', NULL)
INSERT INTO [dbo].[Answers] ([Id], [Content], [CreatedDate], [QuestionId], [AppUserId], [UpdatedDate]) VALUES (17, N'<p>To start, how much do you know?</p><p>What is this? Is it the advertisements? Building the buildings? Owning a restaurant? What?</p><p>Do you want to do Web Development or build software? Do you want to do Front End programming or Back End? What industry do you want to work in? Games? Biotech? SaaS?</p><p>Do you want to learn how to program for yourself and to just have fun?</p><p>Answer these questions first, and then look for resources. As long as Net Neutrality reigns, there are a plethora of free resources for beginners. These two</p><p><a href=""https://www.codecademy.com/"" target=""_blank"">Codecademy - learn to code, interactively, for free</a>,</p><p><a href=""https://www.freecodecamp.org/"" target=""_blank"">Learn to code with free online courses, programming projects, and interview preparation for developer jobs</a>&nbsp;are just a few.</p><p>After doing some coding in these free resources, you need to REFLECT. Is this the type of work you enjoy? Is it something you want to do? Could you safely devote time and resources to it and push yourself very hard towards this goal?</p><p>If you say yes to this, and your true aim is to learn to program quickly, then maybe a code bootcamp is right for you. Research to find a good one. Keep in mind they will cost you money in the range of 10k, and keep in mind that you pay for what you get. You will need to be dedicated. I am talking going to classes, paying attention, asking questions, leaving the classes and going home and coding and reading and using free resources and coding and practicing and making side projects that are not homework and coding and getting on to Quora and Stack Exchange and Github and Codewars and&nbsp;<a href=""http://codepen.io/"" target=""_blank"">CodePen</a>&nbsp;and working your ass off.</p><p>But all of that is if you want a quick turn around, a couple of months.</p><p>If you have the luxury of a little more time, Codeschool and Pluralsight would be good recommendations and way way cheaper than a code bootcamp. You can learn at your own pace, but will still have to work hard. And you’ll have questions these sites won’t answer, so you’ll probably have to buy books or find a programmer you could bug without them minding too much. But you still need to build projects while learning, build side projects, passion projects, build, look at best practices, and learn.</p><p>The world of programming is an accessible one, but it is vast and complex and can be daunting. If a speedy path to proficiency is truly your goal, you will need to spend much of your time, weekends too, devoted to it.</p><p>Good luck.</p>', N'2018-01-17 16:42:58', 21, N'aa32eb82-d698-468e-8c0b-dc3a6bebfc12', N'2018-01-17 16:46:29')
INSERT INTO [dbo].[Answers] ([Id], [Content], [CreatedDate], [QuestionId], [AppUserId], [UpdatedDate]) VALUES (18, N'<p><strong><span class=""ql-cursor"">﻿</span>Space ship battle scenes.</strong></p><p><img src=""https://qph.ec.quoracdn.net/main-qimg-97f09ff2907144af03dcd267d00e7e7f.webp""></p><p>Just consider the following.</p><p>Two thousand years ago, humans used bows and arrows as their primary long - range weapon of choice.</p><p>One thousand years ago, humans could fire projectiles to greater distances, with payloads of greater masses, thanks to the catapult.</p><p>Seven hundred years ago, humans increased their distance, their payload, and decrease their reloading time, by inventing the cannon.</p><p><img src=""https://qph.ec.quoracdn.net/main-qimg-dd191726557c0c30a22bf82bf648df1f.webp""></p><p>Seventy five years ago, the first weaponized rocket was mass produced for a modern conflict, the V-2 rocket, which had a range of 300 km, with a payload that weighed about a ton.</p><p>Nowadays, in 2018, we have mass produced ICBM’s that can reach targets over 5,500 km, and long range artillery that can accurately hit a target 40km away, firing six rounds a minute.</p><p><em>WWII battleship firing its cannons.</em></p><p><img src=""https://qph.ec.quoracdn.net/main-qimg-60b6d4466e15ee19e78d3d2feec07932.webp""></p><p>Now, humanity is at least another thousand years away from engaging in any space wars, giving us plenty of time to perfect our ranged weapons.</p><p>When space wars do happen, I’d imagine we would be bombing each other half way across the galaxy, using weapons with ranges in the millions of km, instead of engaging in close range combat, losing thousands of ships.</p><p>I mean, if you know where the enemy fleet is, since you hyper warped right into their position and engaged in close combat, why don’t you just launch a super plasma rail gun at them from 100,000 km away and save everyone the trouble?</p>', N'2018-01-17 17:13:51', 22, N'eb5d625e-aa8f-4709-a296-f92b1df0dd3e', N'2018-01-17 17:21:21')
INSERT INTO [dbo].[Answers] ([Id], [Content], [CreatedDate], [QuestionId], [AppUserId], [UpdatedDate]) VALUES (19, N'<p><strong>Inception</strong></p><p>Undoubtedly, one of the greatest movies ever made. My observation may be inaccurate so feel free to correct me. Understanding the plot itself was a difficult task. Had to see the movie several times to get a hold of it ( phew ).</p><p>So here we go</p><p>Remember this safe scene in the climax ?</p><p><img src=""https://qph.fs.quoracdn.net/main-qimg-92f17ba7a4843de767a078841ef7c409.webp""></p><p>Can you read it ? the numbers ?</p><p>Yes ? Good !!</p><p>This happens in a dream within a dream right ?</p><p>well ..</p><p>as a matter of fact you<strong>&nbsp;can’t read&nbsp;</strong>while you are dreaming.</p>', N'2018-01-17 19:06:43', 22, N'e40ee71a-e3de-4b33-a877-0cc91fdcb337', NULL)
SET IDENTITY_INSERT [dbo].[Answers] OFF
            ");
        }
        
        public override void Down()
        {
        }
    }
}
