namespace iKnow.Migrations {
    using System;
    using System.Data.Entity.Migrations;

    public partial class SeedTopics : DbMigration {
        public override void Up() {
            Sql(@"
DELETE FROM [dbo].[Topics] WHERE [Name] = N'Software Engineering'
INSERT INTO [dbo].[Topics] ([Name], [Description]) VALUES (N'Software Engineering', N'Software engineering is the process of analyzing user needs and designing, constructing, and testing end user applications that will satisfy these needs through the use of software programming languages. It is the application of engineering principles to software development. 

In contrast to simple programming, software engineering is used for larger and more complex software systems, which are used as critical systems for businesses and organizations.')
INSERT INTO [dbo].[Topics] ([Name], [Description]) VALUES (N'New Zealand', N'New Zealand is an island country located in the southwestern Pacific Ocean comprising two main landmasses (the North Island and the South Island) and numerous smaller islands. 

The geography of New Zealand is highly varied, from snowcapped mountains to lowland plains. The government system is a parliamentary democracy and a Commonwealth realm; the chief of state is the queen of the United Kingdom, and the head of government is the prime minister. New Zealand has a free market economy in which the prices of goods and services are determined in a free price system.')
INSERT INTO [dbo].[Topics] ([Name], [Description]) VALUES (N'Internet', N'The Internet is the global system of interconnected computer networks that use the Internet protocol suite (TCP/IP) to link devices worldwide. It is a network of networks that consists of private, public, academic, business, and government networks of local to global scope, linked by a broad array of electronic, wireless, and optical networking technologies.')
INSERT INTO [dbo].[Topics] ([Name], [Description]) VALUES (N'Artificial Intelligence', N'Artificial intelligence is a science and technology based on disciplines such as Computer Science, Biology, Psychology, Linguistics, Mathematics, and Engineering. A major thrust of AI is in the development of computer functions associated with human intelligence, such as reasoning, learning, and problem solving.')
INSERT INTO [dbo].[Topics] ([Name], [Description]) VALUES (N'History', N'The study of past events, particularly in human affairs.')
INSERT INTO [dbo].[Topics] ([Name], [Description]) VALUES (N'Travel', N'Travel is the movement of people between relatively distant geographical locations, and can involve travel by foot, bicycle, automobile, train, boat, bus, airplane, or other means, with or without luggage, and can be one way or round trip. Travel can also include relatively short stays between successive movements.')
INSERT INTO [dbo].[Topics] ([Name], [Description]) VALUES (N'Web Development', N'Web development is a broad term for the work involved in developing a web site for the Internet (World Wide Web) or an intranet (a private network).')
INSERT INTO [dbo].[Topics] ([Name], [Description]) VALUES (N'Health', N'Health is the level of functional and metabolic efficiency of a living organism. In humans it is the ability of individuals or communities to adapt and self-manage when facing physical, mental, psychological and social changes with environment.')
INSERT INTO [dbo].[Topics] ([Name], [Description]) VALUES (N'Automobile', N'An automobile (or a car) is a wheeled motor vehicle used for transportation. Most definitions of car say they run primarily on roads, seat one to eight people, have four tires, and mainly transport people rather than goods.')
INSERT INTO [dbo].[Topics] ([Name], [Description]) VALUES (N'Environment', N'Environment is everything that is around us. It can be living or nonliving things. It includes physical, chemical and other natural forces. Living things live in their environment. They constantly interact with it and adapt themselves to conditions in their environment.')
INSERT INTO [dbo].[Topics] ([Name], [Description]) VALUES (N'Sport', N'Sport includes all forms of competitive physical activity or games which, through casual or organised participation, aim to use, maintain or improve physical ability and skills while providing enjoyment to participants, and in some cases, entertainment for spectators.')
INSERT INTO [dbo].[Topics] ([Name], [Description]) VALUES (N'Economics', N'Economics is the social science that studies the production, distribution, and consumption of goods and services. Economics focuses on the behaviour and interactions of economic agents and how economies work.')
INSERT INTO [dbo].[Topics] ([Name], [Description]) VALUES (N'Education', N'Education is the process of facilitating learning, or the acquisition of knowledge, skills, values, beliefs, and habits. Educational methods include storytelling, discussion, teaching, training, and directed research.')
INSERT INTO [dbo].[Topics] ([Name], [Description]) VALUES (N'Lifestyle', N'Lifestyle is the interests, opinions, behaviours, and behavioural orientations of an individual, group, or culture.')
INSERT INTO [dbo].[Topics] ([Name], [Description]) VALUES (N'International Relations', N'International relations (IR) or international affairs, depending on academic institution, is either a field of political science, an interdisciplinary academic field similar to global studies, or an entirely independent academic discipline in which students take a variety of internationally focused courses in social science and humanities disciplines.')
INSERT INTO [dbo].[Topics] ([Name], [Description]) VALUES (N'Country', N'A country is a region that is identified as a distinct national entity in political geography. A country may be an independent sovereign state or one that is occupied by another state, as a non-sovereign or formerly sovereign political division, or a geographic region associated with sets of previously independent or differently associated people with distinct political characteristics.')
INSERT INTO [dbo].[Topics] ([Name], [Description]) VALUES (N'Interpersonal Communication', N'Interpersonal communication is an exchange of information between two or more people. It is also an area of study and research that seeks to understand how humans use verbal and nonverbal cues to accomplish a number of personal and relational goals.')
INSERT INTO [dbo].[Topics] ([Name], [Description]) VALUES (N'Google', N'Google is an American multinational technology company that specializes in Internet-related services and products. These include online advertising technologies, search, cloud computing, software, and hardware.')
INSERT INTO [dbo].[Topics] ([Name], [Description]) VALUES (N'Huawei', N'Huawei Technologies Co., Ltd. is a Chinese multinational networking and telecommunications equipment and services company headquartered in Shenzhen, Guangdong. It is the largest telecommunications equipment manufacturer in the world, having overtaken Ericsson in 2012.')
INSERT INTO [dbo].[Topics] ([Name], [Description]) VALUES (N'China', N'China is a country in East Asia bordering the East China Sea, Korea Bay, and the South China Sea. Neighboring countries include 14 sovereign states. The terrain is diverse in China with mostly mountains along with deserts in the west and plains in the east.')
INSERT INTO [dbo].[Topics] ([Name], [Description]) VALUES (N'Full Stack Developer', N'The industry definition of a Full Stack Developer is an engineer who can work on different levels of an application stack. The term stack refers to the combination of components and tools that make up the application. The components could be in the front-end or the back-end of the system.

The main objective of full stack engineer is to keep every part of the system running smoothly. A Full Stack Developer can performs tasks ranging from resizing an image or text in a webpage to patching the kernel.')
INSERT INTO [dbo].[Topics] ([Name], [Description]) VALUES (N'Food', N'Food is any substance[1] consumed to provide nutritional support for an organism. It is usually of plant or animal origin, and contains essential nutrients, such as carbohydrates, fats, proteins, vitamins, or minerals. The substance is ingested by an organism and assimilated by the organism''s cells to provide energy, maintain life, or stimulate growth.')
INSERT INTO [dbo].[Topics] ([Name], [Description]) VALUES (N'America', N'The U.S. is a country of 50 states covering a vast swath of North America, with Alaska in the northwest and Hawaii extending the nation¡¯s presence into the Pacific Ocean. Major Atlantic Coast cities are New York, a global finance and culture center, and capital Washington, DC. Midwestern metropolis Chicago is known for influential architecture and on the west coast, Los Angeles'' Hollywood is famed for filmmaking.')
INSERT INTO [dbo].[Topics] ([Name], [Description]) VALUES (N'Business', N'A business (also known as an enterprise, a company, or a firm) is an organizational entity and legal entity made up of an association of people, be they natural, legal, or a mixture of both who share a common purpose and unite in order to focus their various talents and organize their collectively available skills or resources to achieve specific declared goals and are involved in the provision of goods and services to consumers. A business can also be described as an organisation that provides goods and services for human needs.')
INSERT INTO [dbo].[Topics] ([Name], [Description]) VALUES (N'Movie', N'Movies, also known as films, are a type of visual communication which uses moving pictures and sound to tell stories or inform (help people to learn). 

People in every part of the world watch movies as a type of entertainment, a way to have fun. For some people, fun movies can mean movies that make them laugh, while for others it can mean movies that make them cry, or feel afraid.')
INSERT INTO [dbo].[Topics] ([Name], [Description]) VALUES (N'Music', N'Music is a form of art; an expression of emotions through harmonic frequencies. Music is also a form of entertainment that puts sounds together in a way that people like, find interesting or dance to. Most music includes people singing with their voices or playing musical instruments, such as the piano, guitar, drums or violin.')
INSERT INTO [dbo].[Topics] ([Name], [Description]) VALUES (N'Philosophy', N'Philosophy is a way of thinking about the world, the universe, and society. It works by asking very basic questions about the nature of human thought, the nature of the universe, and the connections between them. The ideas in philosophy are often general and abstract. But this does not mean that philosophy is not about the real world. Ethics, for example, asks about the ideas underlying our everyday lives. Metaphysics asks about how the world works and of what it is made.')
INSERT INTO [dbo].[Topics] ([Name], [Description]) VALUES (N'Physics', N'Physics is the natural science that involves the study of matter and its motion and behavior through space and time, along with related concepts such as energy and force.')
INSERT INTO [dbo].[Topics] ([Name], [Description]) VALUES (N'Mobile Phone', N'A mobile phone, known as a cell phone in North America, is a portable telephone that can make and receive calls over a radio frequency link while the user is moving within a telephone service area.')
INSERT INTO [dbo].[Topics] ([Name], [Description]) VALUES (N'Earth', N'Earth is the planet we live on. It is the third planet from the sun. It is the only planet known to have life on it. Lots of scientists think the earth formed around 4.5 billion years ago. It is one of four rocky planets on the inside of the Solar System. The other three are Mercury, Venus and Mars.')
INSERT INTO [dbo].[Topics] ([Name], [Description]) VALUES (N'Programming Language', N'A programming language is a type of written language that tells computers what to do in order to work. Programming languages are used to make all the computer programs and computer software. A programming language is like a set of instructions that the computer follows to do something.')
INSERT INTO [dbo].[Topics] ([Name], [Description]) VALUES (N'Photography', N'Photography is a way of making a picture using a camera. A person who makes pictures using a camera is called a photographer. A picture made using a camera is called a photograph or photo.')
            ");
        }

        public override void Down() {
        }
    }
}
